---

- name: Ensure override folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system/ripe-atlas.service.d
    state: directory
    mode: '0755'
    owner: root

# If folder does not exist, service will fail to start with "code=exited, status=226/NAMESPACE"
- name: Ensure /home/atlas/data folder exists
  ansible.builtin.file:
    dest: /home/atlas/data
    state: directory
    mode: '0755'
    owner: ripe-atlas

- name: Review ripe-atlas systemd options
  ansible.builtin.template:
    src: systemd-override-ripe-atlas.conf.j2
    dest: /etc/systemd/system/ripe-atlas.service.d/override.conf
    mode: '0644'
    owner: root
  notify:
    - Reload systemd
    - Restart ripe-atlas
