---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container | bool

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Restart ripe-atlas
  ansible.builtin.service:
    name: ripe-atlas
    state: restarted
  when:
    - not is_container | bool
